### PR TITLE
try to fix sqlite deadlocks I guess

### PR DESCRIPTION
**Pull request by indirect**
As seen in https://github.com/rails/rails/issues/30937

### CODE REVIEW

**Comment by numist** [comment]
um?

**Comment by indirect** [comment]
I don’t know! Honeybadger said “there was an exception where sqlite says the db is locked”. I think it’s because only one thread can write to the database at a time, and the web server has five threads, and postmark was sending multiple email webhooks requests in parallel?

**Comment by numist** [comment]
Yeah but you set the busy timeout to `5000`? Pretty rare to see writer starvation with human-scale timeouts like that. Are you 100% sure the database is in wal mode? The default journalling mode will put writers in competition with readers, which creates a lot more contention.

**Comment by indirect** [comment]
I am not sure! I have no idea how to adjust this stuff, I said “please use the file at this path kthx”On Jan 8, 2024, at 10:30 PM, Scott Perry ***@***.***> wrote:﻿
Yeah but you set the busy timeout to 5000? Pretty rare to see writer starvation with human-scale timeouts like that. Are you 100% sure the database is in wal mode? The default journalling mode will put writers in competition with readers, which creates a lot more contention.

**Pull request merged**
