### PR TITLE
Customize SQLite configuration

### PR DESCRIPTION
**Pull request by numist**
This is a follow-up to #370. Allowing concurrent readers alongside a single writer should fix the original issue.

There's an opportunity here to also customize the connection's `cache_size`, if we have a good idea of how many SQLite connections the server is running and how much memory is available.

### CODE REVIEW

**Comment by numist** [comment]
dcf026e fixes #474

**Review by indirect — APPROVED** [review]
I could be wrong but it seems like these are already the defaults as of Rails 7.1? https://www.bigbinary.com/blog/rails-7-1-comes-with-an-optimized-default-sqlite3-adapter-connection-configuration

**Comment by indirect** [comment]
This is what I see before applying your patch:

```
[4] pry(main)> Post.connection.execute "PRAGMA main.journal_mode"
   (0.3ms)  PRAGMA main.journal_mode
=> [{"journal_mode"=>"wal"}]
[5] pry(main)> Post.connection.execute "PRAGMA main.synchronous"
   (0.2ms)  PRAGMA main.synchronous
=> [{"synchronous"=>1}]
```

Not 100% sure about whether `1` is the same as `NORMAL`, but it seems like we are already in WAL mode?

**Comment by indirect** [comment]
It does seem like setting `NORMAL` produces the value `1`:

```
[1] pry(main)> Post.connection.execute "PRAGMA main.synchronous=NORMAL"
   (0.0ms)  PRAGMA main.synchronous=NORMAL
=> []
[2] pry(main)> Post.connection.execute "PRAGMA main.synchronous"
   (1.2ms)  PRAGMA main.synchronous
=> [{"synchronous"=>1}]
```

**Pull request merged**
